create table formularios(
	fecha datetime default CURRENT_TIMESTAMP,
	examinador text not null,
	examinador_cedula integer not null,
	cedula integer not null,
	nombre text not null,
	apellido text not null,
	genero text not null,
	edad integer not null,
	estado text not null,
	ednia text not null,
	ednia_zulia text,
	municipio text not null,
	parroquia text not null,

	temporomaxilar_sintoma char default '8',
	temporomaxilar_signo char default '8',
	lesion char default '8',
	lesion_localizacion char default '8',
	lesion_dolor char default '8',
	lesion_color char default '8',
	lesion_tamaño char default '8',
	lesion_consistencia char default '8',
	lesion_morfologia char default '8',
	lesion_numero char default '8',
	flurosis char default '8',
	placa_16V char default '8',
	placa_11V char default '8',
	placa_26V char default '8',
	placa_36L char default '8',
	placa_31V char default '8',
	placa_46L char default '8',
	calculo_16V char default '8',
	calculo_11V char default '8',
	calculo_26V char default '8',
	calculo_36L char default '8',
	calculo_31V char default '8',
	calculo_46L char default '8',
	peridontico_0 char default '8',
	peridontico_1 char default '8',
	peridontico_2 char default '8',
	peridontico_3 char default '8',
	peridontico_4 char default '8',
	peridontico_5 char default '8',
	corona_17 char not null,
	corona_16 char not null,
	corona_15 char not null,
	corona_14 char not null,
	corona_13 char not null,
	corona_12 char not null,
	corona_11 char not null,
	tratamiento_17 char not null,
	tratamiento_16 char not null,
	tratamiento_15 char not null,
	tratamiento_14 char not null,
	tratamiento_13 char not null,
	tratamiento_12 char not null,
	tratamiento_11 char not null,
	corona_21 char not null,
	corona_22 char not null,
	corona_23 char not null,
	corona_24 char not null,
	corona_25 char not null,
	corona_26 char not null,
	corona_27 char not null,
	tratamiento_21 char not null,
	tratamiento_22 char not null,
	tratamiento_23 char not null,
	tratamiento_24 char not null,
	tratamiento_25 char not null,
	tratamiento_26 char not null,
	tratamiento_27 char not null,
	corona_47 char not null,
	corona_46 char not null,
	corona_45 char not null,
	corona_44 char not null,
	corona_43 char not null,
	corona_42 char not null,
	corona_41 char not null,
	tratamiento_47 char not null,
	tratamiento_46 char not null,
	tratamiento_45 char not null,
	tratamiento_44 char not null,
	tratamiento_43 char not null,
	tratamiento_42 char not null,
	tratamiento_41 char not null,
	corona_31 char not null,
	corona_32 char not null,
	corona_33 char not null,
	corona_34 char not null,
	corona_35 char not null,
	corona_36 char not null,
	corona_37 char not null,
	tratamiento_31 char not null,
	tratamiento_32 char not null,
	tratamiento_33 char not null,
	tratamiento_34 char not null,
	tratamiento_35 char not null,
	tratamiento_36 char not null,
	tratamiento_37 char not null,
	erupcion_dentaria_17 char default '8',
	erupcion_dentaria_16 char default '8',
	erupcion_dentaria_15 char default '8',
	erupcion_dentaria_14 char default '8',
	erupcion_dentaria_13 char default '8',
	erupcion_dentaria_12 char default '8',
	erupcion_dentaria_11 char default '8',
	erupcion_dentaria_21 char default '8',
	erupcion_dentaria_22 char default '8',
	erupcion_dentaria_23 char default '8',
	erupcion_dentaria_24 char default '8',
	erupcion_dentaria_25 char default '8',
	erupcion_dentaria_26 char default '8',
	erupcion_dentaria_27 char default '8',
	erupcion_dentaria_47 char default '8',
	erupcion_dentaria_46 char default '8',
	erupcion_dentaria_45 char default '8',
	erupcion_dentaria_44 char default '8',
	erupcion_dentaria_43 char default '8',
	erupcion_dentaria_42 char default '8',
	erupcion_dentaria_41 char default '8',
	erupcion_dentaria_31 char default '8',
	erupcion_dentaria_32 char default '8',
	erupcion_dentaria_33 char default '8',
	erupcion_dentaria_34 char default '8',
	erupcion_dentaria_35 char default '8',
	erupcion_dentaria_36 char default '8',
	erupcion_dentaria_37 char default '8',
	protesis_necesidad_superior char default '8',
	protesis_necesidad_inferior char default '8',
	protesis_tipo_superior char default '8',
	protesis_tipo_inferior char default '8',
	habitos_bruxismo char default '8',
	habitos_respiracion_bucal char default '8',
	habitos_deglucion_atipica char default '8',
	habitos_succion_digital char default '8',
	habitos_ninguno char default '8',
	relacion_oclusion_2dos_molares char default '8',
	relacion_oclusion_1ros_molares char default '8',
	apiñamiento char not null,
	espaciamiento char not null,
	diastema char not null,
	mordida_abierta char not null,
	morida_profunda_anterior char not null,
	morida_tope_a_tope char not null,
	mordida_cruzada char not null,
	necesidad_asistencia_trastorno char not null,
	necesidad_asistencia_dolor char not null,
	
	exportado int default 0
);

create trigger habitos_ninguno_set after insert on formularios
for each row
begin
	update formularios set habitos_ninguno = 1 where 
		fecha = new.fecha and
		habitos_bruxismo = 0 and 
		habitos_respiracion_bucal = 0 and 
		habitos_deglucion_atipica = 0 and 
		habitos_succion_digital = 0;
	update formularios set habitos_ninguno = 0 where 
		fecha = new.fecha and (
			habitos_bruxismo != 0 or 
			habitos_respiracion_bucal != 0 or 
			habitos_deglucion_atipica != 0 or 
			habitos_succion_digital != 0
		);
end;

create table usuarios(
	cedula integer primary key,
	nombre text,
	password text,
	estado text,
	tipo text
);

create table configuracion(
	ip text
);
insert into configuracion values('');
insert into usuarios values(1, 'Admin', '356a192b7913b04c54574d18c28d46e6395428ab', '', '');
