create table formularios(
	fecha datetime default CURRENT_TIMESTAMP,
	examinador text not null,
	examinador_cedula integer not null,
	cedula integer not null,
	nombre text not null,
	apellido text not null,
	genero text not null,
	edad integer not null,
	estado text not null,
	municipio text not null,

	temporomaxilar_sintoma char,
	temporomaxilar_signo char,
	intraoral_lesion_localizacion char,
	intraoral_lesion_dolor char,
	intraoral_lesion_color char,
	intraoral_lesion_tamaño char,
	intraoral_lesion_consistencia char,
	intraoral_lesion_morfologia char,
	intraoral_lesion_numero char,
	intraoral_flurosis char,
	placa_16V char,
	placa_11V char,
	placa_26V char,
	placa_36L char,
	placa_31V char,
	placa_46L char,
	calculo_16V char,
	calculo_11V char,
	calculo_26V char,
	calculo_36L char,
	calculo_31V char,
	calculo_46L char,
	peridontico_0 char,
	peridontico_1 char,
	peridontico_2 char,
	peridontico_3 char,
	peridontico_4 char,
	peridontico_5 char,
	corona_17 char not null,
	corona_16 char not null,
	corona_15 char not null,
	corona_14 char not null,
	corona_13 char not null,
	corona_12 char not null,
	corona_11 char not null,
	tratamiento_17 char not null,
	tratamiento_16 char not null,
	tratamiento_15 char not null,
	tratamiento_14 char not null,
	tratamiento_13 char not null,
	tratamiento_12 char not null,
	tratamiento_11 char not null,
	corona_21 char not null,
	corona_22 char not null,
	corona_23 char not null,
	corona_24 char not null,
	corona_25 char not null,
	corona_26 char not null,
	corona_27 char not null,
	tratamiento_21 char not null,
	tratamiento_22 char not null,
	tratamiento_23 char not null,
	tratamiento_24 char not null,
	tratamiento_25 char not null,
	tratamiento_26 char not null,
	tratamiento_27 char not null,
	corona_47 char not null,
	corona_46 char not null,
	corona_45 char not null,
	corona_44 char not null,
	corona_43 char not null,
	corona_42 char not null,
	corona_41 char not null,
	tratamiento_47 char not null,
	tratamiento_46 char not null,
	tratamiento_45 char not null,
	tratamiento_44 char not null,
	tratamiento_43 char not null,
	tratamiento_42 char not null,
	tratamiento_41 char not null,
	corona_31 char not null,
	corona_32 char not null,
	corona_33 char not null,
	corona_34 char not null,
	corona_35 char not null,
	corona_36 char not null,
	corona_37 char not null,
	tratamiento_31 char not null,
	tratamiento_32 char not null,
	tratamiento_33 char not null,
	tratamiento_34 char not null,
	tratamiento_35 char not null,
	tratamiento_36 char not null,
	tratamiento_37 char not null,
	erupcion_dentaria_17 char,
	erupcion_dentaria_16 char,
	erupcion_dentaria_15 char,
	erupcion_dentaria_14 char,
	erupcion_dentaria_13 char,
	erupcion_dentaria_12 char,
	erupcion_dentaria_11 char,
	erupcion_dentaria_21 char,
	erupcion_dentaria_22 char,
	erupcion_dentaria_23 char,
	erupcion_dentaria_24 char,
	erupcion_dentaria_25 char,
	erupcion_dentaria_26 char,
	erupcion_dentaria_27 char,
	erupcion_dentaria_47 char,
	erupcion_dentaria_46 char,
	erupcion_dentaria_45 char,
	erupcion_dentaria_44 char,
	erupcion_dentaria_43 char,
	erupcion_dentaria_42 char,
	erupcion_dentaria_41 char,
	erupcion_dentaria_31 char,
	erupcion_dentaria_32 char,
	erupcion_dentaria_33 char,
	erupcion_dentaria_34 char,
	erupcion_dentaria_35 char,
	erupcion_dentaria_36 char,
	erupcion_dentaria_37 char,
	protesis_necesidad_superior char,
	protesis_necesidad_inferior char,
	protesis_tipo_superior char,
	protesis_tipo_inferior char,
	habitos_bruxismo char,
	habitos_respiracion_bucal char,
	habitos_deglucion_atipica char,
	habitos_succion_digital char,
	relacion_oclusion_2dos_molares char,
	relacion_oclusion_1ros_molares char,
	apiñamiento char not null,
	espaciamiento char not null,
	diastema char not null,
	mordida_abierta char not null,
	morida_profunda_anterior char not null,
	morida_tope_a_tope char not null,
	mordida_cruzada char not null,
	necesidad_asistencia_trastorno char not null,
	necesidad_asistencia_dolor char not null,
	
	exportado int default 0
);

create table usuarios(
	cedula integer primary key,
	nombre text,
	password text,
	estado text,
	tipo text
);

insert into usuarios values
(28715209, 'Luis Dubuc', '005a36784a0ea769daf5ccfae4e48a2b8f6445eb', 'Activo', 'Regular'),
(1, 'Admin', '356a192b7913b04c54574d18c28d46e6395428ab', 'Activo', 'Administrador');
